### ISSUE TITLE
Keep April 1st website 

### ISSUE THREAD

**Issue by Kore-Development** [PurpurMC/PurpurWebsite#12]
I don't know if this is the right place to suggest this, but I suggest that the April 1st, 2022 version of the website should be kept, but on a subdomain. For example, on free.purpurmc.org like how Discord has an easter egg at printer.discord.com.

**Comment by Kore-Development** [comment]
The website is perfection btw lol

**Comment by craftish37** [comment]
1st april is always perfection on Purpur.

**Comment by theomega24** [comment]
I've uploaded the source code to the `april-fools/2022` branch, but I don't think running & maintaining this website is a smart use of our time.

**Comment by Encode42** [comment]
I started work on this idea yesterday. It shouldn't be hard to host `/` and `/downloads` on a different domain, then redirect all other requests to the normal domain. This means the docs and such won't fall out of date.

**Comment by Encode42** [comment]
Closing this since it's accessible at https://geocities.purpurmc.org
