### ISSUE TITLE
Javadoc button

### ISSUE THREAD

**Issue by CDFN** [PurpurMC/PurpurWebsite#17]
It would be nice to have link which leads to javadocs ;)

**Comment by Encode42** [comment]
https://purpurmc.org/javadoc?

**Comment by CDFN** [comment]
Yeah but I meant putting it as button on landing page. This way newcomers will know that javadocs is even a thing.

**Comment by BillyGalbreath** [comment]
If you click on that big button that says "Fully Documented" you'll find this https://purpurmc.org/docs/#javadoc

We also link to it from our github readme https://github.com/PurpurMC/Purpur#javadoc

**Comment by CDFN** [comment]
I think that's kind of too much hidden, I had no idea those features are even clickable. I'd consider this issue as UX improvement then.

**Comment by BillyGalbreath** [comment]
Hmm. We could add big red arrows

![image](https://user-images.githubusercontent.com/332527/180851389-9c04e15e-0542-42ed-8161-096b768fd556.png)

**Comment by CDFN** [comment]
Well, if you don't consider this as possible improvement then maybe it's just me.
