### ISSUE TITLE
Cloudflare block curl calls on api.purpurmc.org

### ISSUE THREAD

**Issue by ThisIsAreku** [PurpurMC/PurpurWebsite#8]
Cloudflare DDoS protection randomly block curl calls and return a 503 error with a js captcha, breaking scripts.    
```
$ curl -f https://api.purpurmc.org/v2/purpur
curl: (22) The requested URL returned error: 503
```

**Comment by Encode42** [comment]
Should be fixed by now. Let us know if the issue persists.
